# Generated by Django 3.1.4 on 2021-01-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210113_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='follower_user_id',
            new_name='follower_user',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
