# Generated by Django 3.1.4 on 2021-02-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='width',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
    ]
